version: '3.8'

services:
  api:
    build: .
    volumes:
      - static_volunme:/Workspace/static
    command: gunicorn shuroop.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  redis:
      image: redis:5
      container_name: redis_boot
      hostname: redis_boot
      ports:
        - 6379:6379

  nginx:
    build: ./nginx
    volumes:
      - static_volunme:/Workspace/static
    ports:
      - 80:80
    
    depends_on:
      - api

volumes:
  postgres_data:
  static_volunme:
