version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - static_volunme:/home/app/web/static
    command: gunicorn shuroop.wsgi_dev:application -w 4 --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - asgi
    expose:
      - 8000

  asgi:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: uvicorn shuroop.asgi_dev:application --host 0.0.0.0 --port 9000
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - redis
    expose:
      - 9000

  redis:
      image: redis:5
      container_name: redis_boot
      hostname: redis_boot
      ports:
        - 6379:6379

  nginx:
    build: ./nginx
    volumes:
      - static_volunme:/home/app/web/static
    ports:
      - 80:80
    
    depends_on:
      - api

volumes:
  static_volunme:
