# Generated by Django 4.0.6 on 2022-08-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('umbrella_count', models.IntegerField(default=0)),
                ('max_count', models.IntegerField()),
                ('is_empty', models.BooleanField()),
                ('is_full', models.BooleanField()),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_time', models.DateTimeField(auto_created=True)),
                ('is_renting', models.BooleanField(default=True)),
                ('return_time', models.DateTimeField()),
                ('over_time', models.DurationField()),
                ('charge', models.IntegerField(default=0)),
                ('borrow_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_place', to='rentals.place')),
                ('return_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_place', to='rentals.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='rentals.position'),
        ),
    ]
