# Generated by Django 4.0.6 on 2022-09-02 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_place_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='over_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
