# Generated by Django 4.0.6 on 2022-10-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rentals', '0004_alter_record_over_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='borrow_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='return_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='FavoritePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_place', to='rentals.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSearchPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_place', to='rentals.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
