# Generated by Django 4.0.6 on 2022-09-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('notice_type', models.CharField(choices=[('new_rental', 'New Rental'), ('close_rental', 'Close Rental'), ('over_rental_time', 'Over Rental Time'), ('come_up_return', 'Come Up Return'), ('weather_notice', 'Weather Notice')], default=None, max_length=20)),
                ('content', models.CharField(max_length=50)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
