# This is a basic workflow to help you get started with Actions

name: Code Deploy to AWS

# Controls when the workflow will run
on:

  pull_request:
    branches: [ "release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install SSH key of target
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          name: id_rsa-target
          known_hosts: ${{ secrets.HOST }} # will be appended to existing .ssh/known_hosts
      
      - run: ls /home/runner/.ssh/
      
      - name: Deploy and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username : ${{secrets.USER}}
          port : ${{secrets.PORT}}
          key: /home/runner/.ssh
          script: |
            cd ${{secrets.PATH}}
            git pull origin release
            sh cd.sh
