# This is a basic workflow to help you get started with Actions

name: Code Deploy to AWS

# Controls when the workflow will run
on:
  push:
    branches: [ "release"]
  pull_request:
    branches: [ "release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Deploy and Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username : ${{secrets.USERNAME}}
          password : ${{secrets.PASSWORD}}
          port : ${{secrets.PORT}}
          script: |
            cd ${{secrets.PATH}}
            docker-compose down
            git pull origin release
            docker-compose up --build -d
